### PR TITLE
Bobs commit

### PR DESCRIPTION
**Pull request by Robertght**
MUAHAHAHAHHA breaking the internet

### CODE REVIEW

**Comment by Robertght** [comment]
Hello! ARE YOU THERE!

**Comment by Robertght** [comment]
WHY ARE YOU WRITING IN CAPS?!

**Review by kspilarski — CHANGES_REQUESTED** [review]
Kel texts....

**Review by kdevnel — COMMENTED** [review]
This looks a bit sketchy.

**Comment by Robertght** [comment]
Base64 fix.

**Pull request merged**
